homeView layout
TeamNobar/Nobar-Android pull request #9
Opened 2022-07-08 11:37 UTC by hyeonjeongs

homeView layout

2022-07-08 13:06 UTC, malibinYun requested changes

2022-07-08 13:06 UTC, malibinYun commented on app/src/main/java/org/sopt/appzam/nobar_android/presentation/home/HomeFragment.kt
> +    }
HomeFragment()
요렇게 생성하는거랑
HomeFragment.newInstance()
요렇게 생성하는거랑

크게 다른 점이 없어서 newInstance() 메서드는 없는 게 나아 보여 :)

2022-07-08 13:06 UTC, malibinYun commented on app/src/main/java/org/sopt/appzam/nobar_android/presentation/home/HomeFragment.kt
> +    }
우린 DataBinding / ViewBinding 전부 사용하니까 적어도 ViewBinding으로 써두자

2022-07-08 13:06 UTC, malibinYun commented on app/src/main/java/org/sopt/appzam/nobar_android/presentation/home/HomeFragment.kt
> +        // TODO: Use the ViewModel
직접 VIewModelProvider 생성 하는 것 보다 by viewmodels()를 먼저 활용해보자
아직은 ViewModel만드는 데 필요한 파라미터가 없으니까 :)

2022-07-08 13:06 UTC, malibinYun commented on app/build.gradle
> +    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
우리 레거시 서포트가 필요한 뷰가 있을까 ?_?
필요할 때 넣는 건 어때?

2022-07-08 13:12 UTC, hyeonjeongs commented on app/src/main/java/org/sopt/appzam/nobar_android/presentation/home/HomeFragment.kt
> +    }
엇 그러게요! 수정하고 올릴게요~

2022-07-08 13:12 UTC, hyeonjeongs commented on app/src/main/java/org/sopt/appzam/nobar_android/presentation/home/HomeFragment.kt
> +    }
알겠습니다!

2022-07-08 13:13 UTC, hyeonjeongs commented on app/src/main/java/org/sopt/appzam/nobar_android/presentation/home/HomeFragment.kt
> +        // TODO: Use the ViewModel
엇 수정할게요~!

2022-07-08 13:13 UTC, hyeonjeongs commented on app/build.gradle
> +    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
흠 제가 추가한 기억이 없긴한데 빼고 다시  push 할게요~

2022-07-09 05:14 UTC, briandr97 commented on app/src/main/java/org/sopt/appzam/nobar_android/presentation/base/BaseActivity.kt
> +    protected lateinit var binding: T
오 나 안드로이드 시작하고 protected 처음 써봄 ㄷㄷ

2022-07-09 05:29 UTC, briandr97 commented on app/src/main/res/layout/fragment_home.xml
> +            android:id="@+id/textToMakeRecipe"
저는 textLaterReicpe 생각했는데 Later보단 간지 나는 것 같기도 하고... 
textFutureRecipe? textAfterwardRecipe..? 네이밍 어렵네...

2022-07-09 13:34 UTC, hyeonjeongs commented on app/src/main/res/layout/fragment_home.xml
> +            android:id="@+id/textToMakeRecipe"
오 저는 to부정사의 미래적인 의미를 생각했는데 뭔가 저게 더 좋네요~

2022-07-11 05:16 UTC, merged